### ISSUE TITLE
Attributes with similar name root don't use default values

### ISSUE THREAD

**Issue by ngunia** [thoughtbot/factory_girl_rails#173] opened 2015-09-03 20:30 UTC
I have a model, Scheduler, with two fields with similar names, `schedule`(a hash with datetime information) and `schedule_id` (a random alphanumeric ID).  If I try to explicitly set `schedule` when calling `FactoryGirl.create(:scheduler)`, `schedule_id` gets set to nil.  There is some issue with both of these attributes in my factory having the same root name, schedule.  I verified this by refactoring `schedule_id` to be `scheid` in my entire codebase, which caused the factory to generate Scheduler objects correctly.

Here is a slightly simplified but complete example of the use case:

    # Scheduler Factory
    FactoryGirl.define do
      factory :scheduler, class: Scheduler do
        _id { Moped::BSON::ObjectId.new }
        schedule_id { IDHelper::generate_id }
        schedule  { {"on_datetime" => "2015-03-24T10:55:00Z"} }
        created_at { Time.now }
        updated_at { Time.now }
      end
    end

Standard use case:

    schedule1 = FactoryGirl.create(:scheduler)
    puts "schedule1 is #{schedule1.inspect}"

result:

    schedule1 is #<Scheduler _id: 55e88028f53aab3a50000012, _type: nil, created_at: 2015-09-03 17:15:20 UTC, updated_at: 2015-09-03 17:15:20 UTC, schedule_id: "2874e9f4ae394dadaa89dc7790a5de32", schedule: {"on_datetime"=>"2015-03-24T10:55:00Z"}>

In some cases, I need to override the on_datetime attribute:
    
    on_datetime_tomorrow = {"on_datetime"=>(Time.now.utc + 1).iso8601()}
    schedule1 = FactoryGirl.create(:scheduler, schedule: on_datetime_tomorrow)
    puts "schedule1 is #{schedule1.inspect}"

This properly updates `on_datetime`, but it causes the schedule_id evaluate to nil:

    schedule1 is #<Scheduler _id: 55e880a0f53aab49b0000012, _type: nil, created_at: 2015-09-03 17:17:20 UTC, updated_at: 2015-09-03 17:17:20 UTC, schedule_id: nil, schedule: {"on_datetime"=>"2015-09-03T17:17:21Z"}>

**Comment by t4deu** [comment] 2015-09-09 14:52
This is a duplicate of the Factory Girl issue https://github.com/thoughtbot/factory_girl/issues/734

**Closed** 2015-09-21 12:39 UTC
